account/urls.py
from django.urls import path
from .views import user_login, user_signup, user_logout

app_name = "account"

urlpatterns = [
    path('signup/',user_signup, name='user_signup'),
    path('login/',user_login, name='user_login'),
    path('logout/',user_logout, name='user_logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace="todo")),
    path('account/', include('account.urls', namespace="account")),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

todo/urls.py
from django.urls import path
from .views import home, delete_task, update_task

app_name="todo"

urlpatterns = [
    path('', home, name='home'),
    path('update/<slug:slug>/', update_task, name='update_task'),
    path('delete/<slug:slug>/', delete_task, name='delete_task'),
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TodoList(models.Model):
    STATUS_CHOICE = (
        ("In progess", "In progess"),
        ("Completed", "Completed"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    task = models.CharField(verbose_name="Task name",
                            max_length=150, unique=True)
    slug = models.SlugField(max_length=150, unique=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE,
                               default="In progess")
    started_on = models.DateField(auto_now_add=True)
    ended_on = models.DateField(auto_now=True)

    def __str__(self):
        return self.task

account/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class CustomUserCreationForm(UserCreationForm):
    model = User
    fields = ('username', 'password1', 'password2')

    username = forms.CharField(label="Enter Username :", widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                                'class': 'form-control form-control-lg',
                                                                }))
    password1 = forms.CharField(label="Enter Password :",widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                'class': 'form-control form-control-lg',
                                                                }))
    password2 = forms.CharField(label="Confirm Password :",widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                'class': 'form-control form-control-lg',
                                                                }))
    

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                                'class': 'form-control form-control-lg',
                                                                }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                'class': 'form-control form-control-lg',
                                                                }))

todo/forms.py
from django import forms
from .models import TodoList

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('task',)

class TodoListUpdateForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('task','status')

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import CustomUserCreationForm, LoginForm

# Create your views here.

def user_signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('todo:home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'account/signup.html', {'form':form})

def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password =form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('todo:home')
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form':form})

def user_logout(request):
    logout(request)
    return redirect('todo:home')

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoList
from .forms import TodoListForm, TodoListUpdateForm
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.views.generic import FormView, ListView, CreateView,DeleteView,UpdateView
from django.views.generic.edit import FormMixin



# Create your views here.

@login_required(login_url='account/login')
def home(request):
    task_list = TodoList.objects.filter(user=request.user)
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            slug = slugify(form.cleaned_data['task'])
            task.user = request.user
            task.slug = slug
            task.save()
            return redirect('todo:home')
    form = TodoListForm()
    context = {
        "form":form,
        'task_list':task_list,
    }
    return render(request, 'todo/index.html', context)


def update_task(request, slug):
    tasks = TodoList.objects.get(slug=slug, user=request.user)
    form = TodoListUpdateForm(request.POST or None, instance=tasks)
    if form.is_valid():
        form.save()
        return redirect('todo:home')
    return render(request, 'todo/update.html',{'form':form})

def delete_task(request,slug):
    task = TodoList.objects.get(slug=slug, user=request.user)
    task.delete()
    return redirect('todo:home')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'todo:home' %}">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'todo:home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_signup' %}">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>
                    </li>
                {% endif %}
                
                
                <li class="nav-item">
                    <p class="nav-link">{{request.user}}</p>
                </li>
                
                </ul>
                
            </div>
            </div>
        </nav>
    </div>


    {% block content %}{% endblock content %}

    {% comment %} Bootstrap Script {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

</body>
</html>

templates/todo/index.html
{% extends 'base.html' %}
{% block title %}
<title>Home</title>
{% endblock title %}

{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3">
            <div class="card-body p-4">
  
              <h4 class="text-center my-3 pb-3">To Do App</h4>
  
              <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST">
                    {% csrf_token %}
                    <div class="col-12">
                        <div class="form-outline">
                            {{form.as_p}}
                        </div>
                    </div>
    
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
              </form>
  
              <table class="table mb-4">
                <thead>
                  <tr>
                    <th scope="col">Todo item</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for task in task_list %}
                    <tr>
                        <td>{{task.task}}</td>
                        <td>{{task.status}}</td>
                        <td>
                          <a href="{% url 'todo:delete_task' task.slug %}" class="btn btn-danger">Delete</a>
                          <a href="{% url 'todo:update_task' task.slug %}" class="btn btn-success ms-1">Edit</a>
                        </td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
  
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/todo/update.html
{% extends 'base.html' %}
{% block content %}
<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST">
                {% csrf_token %}
                <div class="col-12">
                    <div class="form-outline">
                        {{form.as_p}}
                    </div>
                </div>

                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}